import "./globals.css";
import { Inter } from "next/font/google";
import TopBar from "../components/UI/TopBar/TopBar";
import NavBar from "../components/UI/NavBar/NavBar";
import Footer from "../components/UI/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={"App"}>
          <TopBar />
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
